woowa-techcamp-2020/market-5

router.js, server.js
server.js
- 기본 경로를 html로 바꾸는 코드 삭제
router.js
- login endpoint 추가
=> [modify] server.js, router.js 수정

server.js
npm start했을 때 메시지 수정
'Express App on port 8080' -> 'Express App on http://localhost:8080'
=> [modify] server.js 수정

router.js, views/Register/register.pug, views/register.pug
회원가입 페이지를 세분화
agreeInfo.pug -> 약관 관련
chooseInfo.pug -> 선택 정보 관련
essentialInfo.pug -> 필수 정보 관련
title -> 타이틀 관련
=> [add] register pug 세분화

package.json
=> [revise] jest 추가

public/css/normalize.css, public/css/register/register.css
* css 호환성을 위한 normalize 코드
* 회원가입 페이지 전반에 공통적인 코드
=> [add] 정적 파일을 위한 public 디렉토리 생성

server.js, views/Register/register.pug, views/Register/title.pug
정적 파일 경로를 public directory로 설정
=> [revise] server.js 수정

public/css/register/agreeInfo.css, public/css/register/chooseInfo.css, public/css/register/register.css, public/css/register/registerButton.css, router.js, views/Register/agreeInfo.pug, views/Register/chooseInfo.pug, views/Register/register.pug, views/Register/registerButton.pug
* register.pug, register.css conflict 해결
* 회원가입 페이지 완성
=> conflict 해결 후 merge 요청

public/css/normalize.css, public/css/register/register.css
* box-sizing 전역에 적용
* big-box에 border 삭제
* big-box height 삭제
=> [revise] register.css, register.pug 수정

public/css/register/essentialInfo.css
=> [revise] input width 수정

public/css/register/essentialInfo.css, views/Register/essentialInfo.pug
=> [revise] email and phone css 수정

public/css/login.css, views/login.pug
login 페이지 pug,css 추가
register js폴더 및 파일 추가
=> login pug and css / register js

package.json, public/css/normalize.css, public/css/register/chooseInfo.css, public/css/register/essentialInfo.css, public/javascripts/register/essentialInfo.js, views/Register/essentialInfo.pug
* 2분 타이머 추가
* 실제 인증번호는 아니고 임시 번호
* 1234를 입력하면 인증, 아니면 틀렸다고 메시지
* 휴대폰 번호 입력 받을때 못 지우는 버그 해결
=> [revise] 휴대폰 인증받는 로직 추가

public/javascripts/register/agreeInfo.js, views/Register/agreeInfo.pug, views/Register/register.pug
* 전체 약관 동의를 누르면 하위 약관 모두 동의
* 전체 약관 동의 해제시 하위 약관 모두 동의 해제
* 하위 약관 중 하나라도 동의가 없으면 전체 약관 동의 해제
* 하위 약관 모두 동의시 자동으로 전체 약관 동의
=> [revise] 약관 관련 로직 추가

public/css/register/chooseInfo.css, public/css/register/register.css, public/javascripts/register/chooseInfo.js, views/Register/chooseInfo.pug, views/Register/register.pug
[add] address modal pug,css …
[add] using kakao api(address) …
=> 주소창 pug,css,js

public/css/register/essentialInfo.css, public/javascripts/register/agreeInfo.js, public/javascripts/register/essentialInfo.js, views/Register/essentialInfo.pug, views/Register/register.pug
=> [reviste] certificate time css 수정

package.json, public/javascripts/register/essentialInfo/verification.js
* pull중 빠진 내용을 추가했습니다
* 핸드폰 인증 시간 css 부분입니다
=> git conflict resolve

.gitignore, package-lock.json, public/javascripts/register/essentialInfo/essentialInfo.js, public/javascripts/register/essentialInfo/formCheck.js, public/javascripts/register/registerButton.js, public/javascripts/utils/nameValidator.test.js, router.js, server.js, views/Register/chooseInfo.pug, views/Register/essentialInfo.pug, views/Register/register.pug
* email 파싱, 필수 동의 여부 정보를 formData에 추가
* formData 관련 태그들에 name 수정
* formData를 urlencoded 형태로 보내기 위해 URLSearchParams 사용
=> formData 전송 & neDB 설치

doubleCheck.js, package.json, router.js, server.js, test.js
* 아이디 중복체크 함수
* 라우터 생성
* 데이터베이스 연동 --> npm i nedb-promises
> nedb를 promise로 사용하기 위해서 위 모듈을 사용했습니다!
* test.js파일은 제가 만든 함수를 테스트해보기 위해서 사용했습니다.
* 이슈를 지금 확인해보니까 register/check/id 이네요 .. idCheck로 전 진행해서 이부분을 바꿔야할듯합니다 ㅎㅎ
=> 아이디 중복체크 함수, 라우터 생성

public/css/register/essentialInfo.css, public/javascripts/register/essentialInfo/essentialInfo.js, public/javascripts/register/essentialInfo/formCheck.js, public/javascripts/utils/nameValidator.js, router.js, server.js, views/Register/essentialInfo.pug
* 중복체크 버튼 추가
* 중복체크 기능 추가
* 아이디 검사 문구 수정
> 중복체크 전에 '사용가능한 아이디입니다'라는 문구를 '중복체크를 해주세요' 로 변경
=> [add] duplicate ui and function

router/login.js, router/middleware/authenticate.js, router/router.js
* sessionID가 없을 경우 /login으로 redirect
=> [revise] authenticate 미들웨어 수정

public/javascripts/register/essentialInfo/formCheck.js, public/javascripts/register/registerButton.js, router/middleware/authenticate.js, views/login.pug, views/mypage.pug
* 절대경로를 상대경로로
* 로그인페이지 쿠키가 미존재시 접속불가, 예외처리 진행
=> 로그인페이지 쿠키 / 절대경로를 상대경로로

router/login.js, views/login.pug
=> 로그인 실패시 오류 메시지

api/register/database.js, api/register/doubleCheck.js, router/login.js, router/main.js, router/mypage.js
=> [revise] db load
